questionnaires = {
    10: [{
        'type': 'select',
        'value': 4
    }, {
        'type': 'input',
        'value': 15
    }, {
        'type': 'select',
        'value': 4
    }, {
        'type': 'select',
        'value': 4
    }, {
        'type': 'select',
        'value': 4
    }, {
        'type': 'select',
        'value': 0
    }, {
        'type': 'select',
        'value': 4
    }, {
        'type': 'select',
        'value': 0
    }, {
        'type': 'select',
        'value': 4
    }, {
        'type': 'select',
        'value': 0
    }],
    9: [{
        'type': 'select',
        'value': 4
    }, {
        'type': 'input',
        'value': 30
    }, {
        'type': 'select',
        'value': 4
    }, {
        'type': 'select',
        'value': 4
    }, {
        'type': 'select',
        'value': 4
    }, {
        'type': 'select',
        'value': 0
    }, {
        'type': 'select',
        'value': 4
    }, {
        'type': 'select',
        'value': 0
    }, {
        'type': 'select',
        'value': 4
    }, {
        'type': 'select',
        'value': 1
    }],
    8: [{
        'type': 'select',
        'value': 3
    }, {
        'type': 'input',
        'value': 30
    }, {
        'type': 'select',
        'value': 3
    }, {
        'type': 'select',
        'value': 3
    }, {
        'type': 'select',
        'value': 3
    }, {
        'type': 'select',
        'value': 0
    }, {
        'type': 'select',
        'value': 4
    }, {
        'type': 'select',
        'value': 1
    }, {
        'type': 'select',
        'value': 3
    }, {
        'type': 'select',
        'value': 1
    }],
    7: [{
        'type': 'select',
        'value': 3
    }, {
        'type': 'input',
        'value': 30
    }, {
        'type': 'select',
        'value': 3
    }, {
        'type': 'select',
        'value': 3
    }, {
        'type': 'select',
        'value': 3
    }, {
        'type': 'select',
        'value': 1
    }, {
        'type': 'select',
        'value': 3
    }, {
        'type': 'select',
        'value': 1
    }, {
        'type': 'select',
        'value': 3
    }, {
        'type': 'select',
        'value': 1
    }],
    6: [{
        'type': 'select',
        'value': 2
    }, {
        'type': 'input',
        'value': 30
    }, {
        'type': 'select',
        'value': 2
    }, {
        'type': 'select',
        'value': 3
    }, {
        'type': 'select',
        'value': 2
    }, {
        'type': 'select',
        'value': 2
    }, {
        'type': 'select',
        'value': 2
    }, {
        'type': 'select',
        'value': 2
    }, {
        'type': 'select',
        'value': 4
    }, {
        'type': 'select',
        'value': 2
    }],
    5: [{
        'type': 'select',
        'value': 2
    }, {
        'type': 'input',
        'value': 30
    }, {
        'type': 'select',
        'value': 2
    }, {
        'type': 'select',
        'value': 2
    }, {
        'type': 'select',
        'value': 2
    }, {
        'type': 'select',
        'value': 2
    }, {
        'type': 'select',
        'value': 2
    }, {
        'type': 'select',
        'value': 2
    }, {
        'type': 'select',
        'value': 2
    }, {
        'type': 'select',
        'value': 2
    }],
    4: [{
        'type': 'select',
        'value': 1
    }, {
        'type': 'input',
        'value': 30
    }, {
        'type': 'select',
        'value': 1
    }, {
        'type': 'select',
        'value': 1
    }, {
        'type': 'select',
        'value': 1
    }, {
        'type': 'select',
        'value': 3
    }, {
        'type': 'select',
        'value': 3
    }, {
        'type': 'select',
        'value': 3
    }, {
        'type': 'select',
        'value': 3
    }, {
        'type': 'select',
        'value': 3
    }],
    3: [{
        'type': 'select',
        'value': 1
    }, {
        'type': 'input',
        'value': 30
    }, {
        'type': 'select',
        'value': 1
    }, {
        'type': 'select',
        'value': 1
    }, {
        'type': 'select',
        'value': 1
    }, {
        'type': 'select',
        'value': 3
    }, {
        'type': 'select',
        'value': 1
    }, {
        'type': 'select',
        'value': 3
    }, {
        'type': 'select',
        'value': 1
    }, {
        'type': 'select',
        'value': 3
    }],
    2: [{
        'type': 'select',
        'value': 1
    }, {
        'type': 'input',
        'value': 40
    }, {
        'type': 'select',
        'value': 1
    }, {
        'type': 'select',
        'value': 0
    }, {
        'type': 'select',
        'value': 0
    }, {
        'type': 'select',
        'value': 4
    }, {
        'type': 'select',
        'value': 0
    }, {
        'type': 'select',
        'value': 4
    }, {
        'type': 'select',
        'value': 0
    }, {
        'type': 'select',
        'value': 4
    }],
    1: [{
        'type': 'select',
        'value': 0
    }, {
        'type': 'input',
        'value': 40
    }, {
        'type': 'select',
        'value': 0
    }, {
        'type': 'select',
        'value': 0
    }, {
        'type': 'select',
        'value': 0
    }, {
        'type': 'select',
        'value': 4
    }, {
        'type': 'select',
        'value': 0
    }, {
        'type': 'select',
        'value': 4
    }, {
        'type': 'select',
        'value': 0
    }, {
        'type': 'select',
        'value': 4
    }],

}

questionnaire_questions={
    1:"What is your primary reason for investing?",
    2:"What is your current age?",
    3: "What is your monthly income (in USD)?",
    4:"What best describes your household?",
    5:"What is the total value of your cash and liquid investments (in USD)?",
    6:"I would rather have lower and predictable investment returns than ones which may be higher, but less predictable.",
    7:"I believe that I generally take bigger investment risks with my money than other people.",
    8:"I worry about losing money in the stock market.",
    9:"If there's a chance of making better long-term returns, I am willing to take an investment risk.",
    10:"I would be worried if I saw my investments had gone down in value."
}


